# Site settings
title: Angular Architecture
email: greg@greg-jacobs.com
description: > # this means to ignore newlines until "baseurl:"
  Guides about AngularJS 1.x architecture, testing, and general best
  practices.
url: "http://gregjacobs.github.io" # the base hostname & protocol for your site
baseurl: "/Angular-Architecture" # the subpath of your site, e.g. /blog/
github_username: gregjacobs

# Build settings
markdown: redcarpet