# Site settings
title: Angular Guides
email: greg@greg-jacobs.com
description: > # this means to ignore newlines until "baseurl:"
  Guides about AngularJS development, architecture, testing, and general best
  practices developed over the years.
url: "http://gregjacobs.github.io" # the base hostname & protocol for your site
baseurl: "/Angular-Guides" # the subpath of your site, e.g. /blog/
github_username: gregjacobs

# Build settings
markdown: redcarpet